### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by AndreasVolkmann** [KotlinNLP/SimpleDNN#2]
Is there any maven repository yet?

I can see there is some JCenter stuff in the pom, but I cannot find the repo.

**Comment by KotlinNLP** [comment]
Hi, we plan to deploy on maven central by the end of next week.

**Comment by KotlinNLP** [comment]
**Apache Maven**
```
<dependency>
    <groupId>com.kotlinnlp</groupId>
    <artifactId>simplednn</artifactId>
    <version>0.1.0</version>
</dependency>
```
